environment: development

nats:
  url: nats://127.0.0.1:4222
  username: ""
  password: ""

runtime:
  participant_id: node0
  identity_ref: node0
  identity_store_dir: ./node0/sdkflow
  peer_ready_timeout: 10s
  peer_ready_interval: 300ms
  ecdsa_preparams_path: ./node0/preparams.json
  request_timeout: 45s

storage:
  root_dir: ./node0/sdkflow-state

consumer:
  max_concurrent_keygen: 2
  max_concurrent_sign: 4
